### ISSUE TITLE
Interesting library

### ISSUE THREAD

**Issue by tmaszk** [wfgilman/yodlee-elixir#1]
Thanks for posting this library, it looks like it will be useful.  I tried it this morning and ran into a few problems.  

The README says to add `:yodlee` to the dependencies in `mix.exs`, but that is a hex package from another developer.  Your package appears to be called `:yodlee_elixir` on hex.

I added `:yodlee_elixir` to the dependencies in `mix.exs`, which does pull in your package, but when the project is compiled, it produces the following:
```
Unchecked dependencies for environment test:
* yodlee_elixir (Hex package)
  could not find an app file at "_build/test/lib/yodlee_elixir/ebin/yodlee_elixir.app". This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

I was able to successfully add your package directly from github with this entry in the dependencies.
```elixir
[{:yodlee, git: "https://github.com/wfgilman/yodlee-elixir.git"}]
```

It would be great to fix the hex package, but I don't mind linking to the github project if necessary.

Also, it is minor, but the example config in the README is missing a comma at the end of the line
```elixir
cobrand_password: "your_cobrand_password"
```

**Comment by wfgilman** [comment]
Thanks for catching that! Due to the name conflict `hex: :yodlee_elixir` needs to be added to the `deps/0` function.

`{:yodlee, "~>0.1", hex: :yodlee_elixir}`

I've updated the README to reflect this.

**Comment by tmaszk** [comment]
Thanks!  I didn’t know you could specify it that way.  That’s great.

TOm
